version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI:-mongodb://root:wNbSKJw096Jnz2tSioZdr8wOztNOFNU1i14LTC5zinXzTYJdjSnamupFikv8nPVG@147.93.36.93:27017/bayres-panel?directConnection=true}
      - JWT_SECRET=${JWT_SECRET:-secretkeyfordev}
      - PORT=3000
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - bayres-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=bayres
    restart: unless-stopped
    networks:
      - bayres-network

volumes:
  mongodb_data:
    driver: local

networks:
  bayres-network:
    driver: bridge 